In [2]:
import numpy as np
import pandas as pd
import plotly.graph_objects as go

In [31]:
def clean_csv(path: str) -> pd.DataFrame:
    with open(path, "r") as f:
        lines = [line.strip().split(",") for line in f]
        
    n_cols = max(len(line) for line in lines)
    normalized = [line + [""] * (n_cols - len(line)) if len(line) < n_cols else line[:n_cols] for line in lines]
    df = pd.DataFrame(normalized)
    df.replace('', np.nan, inplace=True)
    if path == 'Output/LS_ControlVariate_Simulations_Convergence_CallLaguerreBermudanBasket.csv':
        full_index = list(range(50, 1050, 50)) + list(range(2000, 4001, 2000))
        df = df.iloc[:-3, :]
    elif path == "Outputs/LS_Antithetic_ControlVariate_Simulations_Convergence_CallLaguerreBermudanBasket.csv":
        full_index = list(range(50, 1050, 50)) + list(range(2000, 4001, 2000))
        df = df.iloc[:-3, :]
    elif path == "Outputs/Quasi_LS_ControlVariate_Simulations_Convergence_CallBermudanBasket.csv":
        full_index = list(range(50, 1050, 50)) + list(range(2000, 4001, 2000))
        df = df.iloc[:-3, :]
    elif path == "Outputs/QuasiLS_Antithetic_ControlVariate_Simulations_Convergence_CallBermudanBasket.csv":
        full_index = list(range(50, 1050, 50)) + list(range(2000, 4001, 2000))
        df = df.iloc[:-3, :]
    elif path == "Outputs/QuasiLS_Antithetic_ControlVariate_Simulations_Convergence_CallLaguerreBermudanBasket.csv":
        full_index = list(range(50, 1050, 50)) + list(range(2000, 4001, 2000))
        df = df.iloc[:-3, :]
    elif path == "Outputs/Quasi_LS_ControlVariate_Simulations_Convergence_CallLaguerreBermudanBasket.csv":
        full_index = list(range(50, 1050, 50)) + list(range(2000, 4001, 2000))
        df = df.iloc[:-3, :]
    elif "ControlVariate" in path and "Basket" in path:
        full_index = list(range(50, 1050, 50)) + list(range(2000, 6001, 2000))
        df = df.iloc[:-2, :]
    else:
        full_index = list(range(50, 1050, 50)) + list(range(2000, 10001, 2000))

    # Adjust index to match df size
    index_values = full_index[:len(df)]

    df.index = index_values
    df.index.name = "nbSim"
    return df


def compute_references(df: pd.DataFrame) -> pd.DataFrame:
    df_res = df.copy()
    df_res["mean"] = df.astype(float).mean(axis=1, skipna=True)
    df_res["var"] = df.astype(float).var(axis=1, skipna=True)
    df_res["var_normalized"] = df_res["var"] / df_res.index
    df_res["ci_margin"] = (df_res["var_normalized"] * 1.96)
    df_res["ci_lower"] = df_res["mean"] - df_res["ci_margin"]
    df_res["ci_upper"] = df_res["mean"] + df_res["ci_margin"]
    return df_res


def summarize_results(df_dict, idx) -> pd.DataFrame:
    summary = {}

    for name, df in df_dict.items():
        mean = df.loc[idx, "mean"]
        var = df.loc[idx, "var_normalized"]
        ci_str = f"[{df.loc[idx, 'ci_lower']:.4f} ; {df.loc[idx, 'ci_upper']:.4f}]"

        summary[name] = {
            "mean": mean,
            "var": var,
            "ci_interval": ci_str
        }

    return pd.DataFrame(summary)

## Standard

In [32]:
# Mono Underlying
call_ls_path = r"Outputs/LS_Simulations_Convergence_Call.csv"
call_ls_cv_path = r"Outputs/LS_ControlVariate_Simulations_Convergence_Call.csv"
call_ls_an_path = r"Outputs/LS_Antithetic_Simulations_Convergence_Call.csv"
call_ls_an_cv_path = r"Outputs/LS_Antithetic_ControlVariate_Simulations_Convergence_Call.csv"

# Basket
call_ls_path_b= r"Outputs/LS_Simulations_Convergence_CallBasket.csv"
call_ls_cv_path_b = r"Outputs/LS_ControlVariate_Simulations_Convergence_CallBasket.csv"
call_ls_an_path_b = r"Outputs/LS_Antithetic_Simulations_Convergence_CallBasket.csv"
call_ls_an_cv_path_b = r"Outputs/LS_Antithetic_ControlVariate_Simulations_Convergence_CallBasket.csv"

# Bermudan Basket
call_ls_path_bb= r"Outputs/LS_Simulations_Convergence_CallBermudanBasket.csv"
call_ls_cv_path_bb = r"Outputs/LS_ControlVariate_Simulations_Convergence_CallBermudanBasket.csv"
call_ls_an_path_bb = r"Outputs/LS_Antithetic_Simulations_Convergence_CallBermudanBasket.csv"
call_ls_an_cv_path_bb = r"Outputs/LS_Antithetic_ControlVariate_Simulations_Convergence_CallBermudanBasket.csv"
call_ls_path_bbq= r"Outputs/QuasiLS_Convergence_CallBermudanBasket.csv"
call_ls_cv_path_bbq = r"Outputs/QuasiLS_ControlVariate_Simulations_Convergence_CallBermudanBasket.csv"
call_ls_an_path_bbq = r"Outputs/QuasiLS_Antithetic_Simulations_Convergence_CallBermudanBasket.csv"
call_ls_an_cv_path_bbq = r"Outputs/QuasiLS_Antithetic_ControlVariate_Simulations_Convergence_CallBermudanBasket.csv"

In [33]:
# Mono Underlying
df_call_ls = clean_csv(call_ls_path)
df_call_ls = compute_references(df_call_ls)

df_call_ls_cv = clean_csv(call_ls_cv_path)
df_call_ls_cv = compute_references(df_call_ls_cv)

df_call_ls_an = clean_csv(call_ls_an_path)
df_call_ls_an = compute_references(df_call_ls_an)

df_call_ls_an_cv = clean_csv(call_ls_an_cv_path)
df_call_ls_an_cv = compute_references(df_call_ls_an_cv)

# Basket
df_call_ls_b = clean_csv(call_ls_path_b)
df_call_ls_b = compute_references(df_call_ls_b)

df_call_ls_cv_b = clean_csv(call_ls_cv_path_b)
df_call_ls_cv_b = compute_references(df_call_ls_cv_b)

df_call_ls_an_b = clean_csv(call_ls_an_path_b)
df_call_ls_an_b = compute_references(df_call_ls_an_b)

df_call_ls_an_cv_b = clean_csv(call_ls_an_cv_path_b)
df_call_ls_an_cv_b = compute_references(df_call_ls_an_cv_b)

# Bermudan Basket
df_call_ls_bb = clean_csv(call_ls_path_bb)
df_call_ls_bb = compute_references(df_call_ls_bb)

df_call_ls_cv_bb = clean_csv(call_ls_cv_path_bb)
df_call_ls_cv_bb = compute_references(df_call_ls_cv_bb)

df_call_ls_an_bb = clean_csv(call_ls_an_path_bb)
df_call_ls_an_bb = compute_references(df_call_ls_an_bb)

df_call_ls_an_cv_bb = clean_csv(call_ls_an_cv_path_bb)
df_call_ls_an_cv_bb = compute_references(df_call_ls_an_cv_bb)

df_call_ls_bbq = clean_csv(call_ls_path_bbq)
df_call_ls_bbq = compute_references(df_call_ls_bbq)

df_call_ls_cv_bbq = clean_csv(call_ls_cv_path_bb)
df_call_ls_cv_bbq = compute_references(df_call_ls_cv_bb)

df_call_ls_an_bbq = clean_csv(call_ls_an_path_bbq)
df_call_ls_an_bbq = compute_references(df_call_ls_an_bbq)

df_call_ls_an_cv_bbq = clean_csv(call_ls_an_cv_path_bbq)
df_call_ls_an_cv_bbq = compute_references(df_call_ls_an_cv_bbq)

## Laguerre

In [34]:
call_ls_path_l = r"Outputs/LS_Simulations_Convergence_CallLaguerre.csv"
call_ls_cv_path_l = r"Outputs/LS_ControlVariate_Simulations_Convergence_CallLaguerre.csv"
call_ls_an_path_l = r"Outputs/LS_Antithetic_Simulations_Convergence_CallLaguerre.csv"
call_ls_an_cv_path_l = r"Outputs/LS_Antithetic_ControlVariate_Simulations_Convergence_CallLaguerre.csv"

# Basket
call_ls_path_lb = r"Outputs/LS_Simulations_Convergence_CallLaguerreBasket.csv"
call_ls_cv_path_lb = r"Outputs/LS_ControlVariate_Simulations_Convergence_CallLaguerreBasket.csv"
call_ls_an_path_lb = r"Outputs/LS_Antithetic_Simulations_Convergence_CallLaguerreBasket.csv"
call_ls_an_cv_path_lb = r"Outputs/LS_Antithetic_ControlVariate_Simulations_Convergence_CallLaguerreBasket.csv"

# Bermudan Basket
call_ls_path_lbb = r"Outputs/LS_Simulations_Convergence_CallLaguerreBermudanBasket.csv"
call_ls_cv_path_lbb = r"Outputs/LS_ControlVariate_Simulations_Convergence_CallLaguerreBermudanBasket.csv"
call_ls_an_path_lbb = r"Outputs/LS_Antithetic_Simulations_Convergence_CallLaguerreBermudanBasket.csv"
call_ls_an_cv_path_lbb = r"Outputs/LS_Antithetic_ControlVariate_Simulations_Convergence_CallLaguerreBasket.csv"
call_ls_path_lbbq = r"Outputs/QuasiLS_Convergence_CallLaguerreBermudanBasket.csv"
call_ls_cv_path_lbbq = r"Outputs/QuasiLS_ControlVariate_Simulations_Convergence_CallLaguerreBermudanBasket.csv"
call_ls_an_path_lbbq = r"Outputs/QuasiLS_Antithetic_Simulations_Convergence_CallLaguerreBermudanBasket.csv"
call_ls_an_cv_path_lbbq = r"Outputs/QuasiLS_Antithetic_ControlVariate_Simulations_Convergence_CallLaguerreBasket.csv"

In [35]:
# Mono Underlying
df_call_ls_l = clean_csv(call_ls_path_l)
df_call_ls_l = compute_references(df_call_ls_l)

df_call_ls_cv_l = clean_csv(call_ls_cv_path_l)
df_call_ls_cv_l = compute_references(df_call_ls_cv_l)

df_call_ls_an_l = clean_csv(call_ls_an_path_l)
df_call_ls_an_l = compute_references(df_call_ls_an_l)

df_call_ls_an_cv_l = clean_csv(call_ls_an_cv_path_l)
df_call_ls_an_cv_l = compute_references(df_call_ls_an_cv_l)


# Basket
df_call_ls_lb = clean_csv(call_ls_path_lb)
df_call_ls_lb = compute_references(df_call_ls_lb)

df_call_ls_cv_lb = clean_csv(call_ls_cv_path_lb)
df_call_ls_cv_lb = compute_references(df_call_ls_cv_lb)

df_call_ls_an_lb = clean_csv(call_ls_an_path_lb)
df_call_ls_an_lb = compute_references(df_call_ls_an_lb)

df_call_ls_an_cv_lb = clean_csv(call_ls_an_cv_path_lb)
df_call_ls_an_cv_lb = compute_references(df_call_ls_an_cv_lb)

# Bermudan Basket
df_call_ls_lbb = clean_csv(call_ls_path_lbb)
df_call_ls_lbb = compute_references(df_call_ls_lbb)

df_call_ls_cv_lbb = clean_csv(call_ls_cv_path_lbb)
df_call_ls_cv_lbb = compute_references(df_call_ls_cv_lbb)

df_call_ls_an_lbb = clean_csv(call_ls_an_path_lbb)
df_call_ls_an_lbb = compute_references(df_call_ls_an_lbb)

df_call_ls_an_cv_lbb = clean_csv(call_ls_an_cv_path_lbb)
df_call_ls_an_cv_lbb = compute_references(df_call_ls_an_cv_lbb)

df_call_ls_lbbq = clean_csv(call_ls_path_lbbq)                # Quasi LS
df_call_ls_lbbq = compute_references(df_call_ls_lbbq)

df_call_ls_cv_lbbq = clean_csv(call_ls_cv_path_lbb)
df_call_ls_cv_lbbq = compute_references(df_call_ls_cv_lbb)

df_call_ls_an_lbbq = clean_csv(call_ls_an_path_lbbq)
df_call_ls_an_lbbq= compute_references(df_call_ls_an_lbbq)

df_call_ls_an_cv_lbbq = clean_csv(call_ls_an_cv_path_lbb)
df_call_ls_an_cv_lbbq = compute_references(df_call_ls_an_cv_lbb)

## Convergence of both algos to MC Prices for European Options

In [36]:
fig = go.Figure()

fig.add_trace(go.Scatter(
    x=df_call_ls.index,
    y=df_call_ls["mean"],
    mode='lines',
    name='LS Average Price'
))

 # ------ Laguerre -----
fig.add_trace(go.Scatter(
    x=df_call_ls_l.index,
    y=df_call_ls_l["mean"],
    mode='lines',
    name='LS Laguerre Average Price'
))


fig.update_layout(
    title="Price Convergence by method of Longstaff Schwarz Algorithms",
    xaxis_title="Number of Simulations",
    yaxis_title="Average Price",
    legend_title="Simulation methods"
)

fig.show()

In [37]:
fig = go.Figure()

# Courbe 1 : Moyenne
fig.add_trace(go.Scatter(
    x=df_call_ls.index,
    y=df_call_ls["var_normalized"],
    mode='lines',
    name='LS Price Variance'
))

# Laguerre
fig.add_trace(go.Scatter(
    x=df_call_ls_l.index,
    y=df_call_ls["var_normalized"],
    mode='lines',
    name='LS Laguerre Price Variance'
))

fig.update_layout(
    title="Variance Convergence by method of Longstaff Schwarz Algorithms",
    xaxis_title="Number of Simulations",
    yaxis_title="Average Variance",
    legend_title="Simulation methods"
)

fig.show()

## Convergence of both algos to MC Prices for European Options on Baskets

In [38]:
fig = go.Figure()

fig.add_trace(go.Scatter(
    x=df_call_ls_b.index,
    y=df_call_ls_b["mean"],
    mode='lines',
    name='LS Average Price'
))

 # ------ Laguerre -----
fig.add_trace(go.Scatter(
    x=df_call_ls_lb.index,
    y=df_call_ls_lb["mean"],
    mode='lines',
    name='LS Laguerre Average Price'
))


fig.update_layout(
    title="Price Convergence by method of Longstaff Schwarz Algorithms",
    xaxis_title="Number of Simulations",
    yaxis_title="Average Price",
    legend_title="Simulation methods"
)

fig.show()

In [39]:
fig = go.Figure()

# Courbe 1 : Moyenne
fig.add_trace(go.Scatter(
    x=df_call_ls_b.index,
    y=df_call_ls_b["var_normalized"],
    mode='lines',
    name='LS Price Variance'
))


# Laguerre
fig.add_trace(go.Scatter(
    x=df_call_ls_lb.index,
    y=df_call_ls_lb["var_normalized"],
    mode='lines',
    name='LS Laguerre Price Variance'
))

fig.update_layout(
    title="Variance Convergence by method of Longstaff Schwarz Algorithms",
    xaxis_title="Number of Simulations",
    yaxis_title="Average Variance",
    legend_title="Simulation methods"
)

fig.show()

## Convergence for Bermudan Baskets

In [25]:
fig = go.Figure()

# fig.add_trace(go.Scatter(
#     x=df_call_ls_bb.index,
#     y=df_call_ls_bb["mean"],
#     mode='lines',
#     name='LS Average Price'
# ))

fig.add_trace(go.Scatter(
    x=df_call_ls_an_bb.index,
    y=df_call_ls_an_bb["mean"],
    mode='lines',
    name='LS Antithetic Average Price'
))

# fig.add_trace(go.Scatter(
#     x=df_call_ls_cv_bb.index,
#     y=df_call_ls_cv_bb["mean"],
#     mode='lines',
#     name='LS Control Variate Average Price'
# ))

# fig.add_trace(go.Scatter(
#     x=df_call_ls_an_cv_bb.index,
#     y=df_call_ls_an_cv_bb["mean"],
#     mode='lines',
#     name='LS Antithetic Control Variate Average Price'
# ))



 # ------ Laguerre -----
fig.add_trace(go.Scatter(
    x=df_call_ls_lbb.index,
    y=df_call_ls_lbb["mean"],
    mode='lines',
    name='LS Laguerre Average Price'
))

fig.add_trace(go.Scatter(
    x=df_call_ls_an_lbb.index,
    y=df_call_ls_an_lbb["mean"],
    mode='lines',
    name='LS Laguerre Antithetic Average Price'
))

fig.add_trace(go.Scatter(
    x=df_call_ls_cv_lbb.index,
    y=df_call_ls_cv_lbb["mean"],
    mode='lines',
    name='LS Laguerre Control Variate Average Price'
))

fig.add_trace(go.Scatter(
    x=df_call_ls_an_cv_lbb.index,
    y=df_call_ls_an_cv_lbb["mean"],
    mode='lines',
    name='LS Laguerre Antithetic Control Variate Average Price'
))


fig.update_layout(
    title="Price Convergence by method of Longstaff Schwarz Algorithms",
    xaxis_title="Number of Simulations",
    yaxis_title="Average Price",
    legend_title="Simulation methods"
)

fig.show()

In [26]:
fig = go.Figure()

# Courbe 1 : Moyenne
fig.add_trace(go.Scatter(
    x=df_call_ls_bb.index,
    y=df_call_ls_bb["var_normalized"],
    mode='lines',
    name='LS Price Variance'
))

fig.add_trace(go.Scatter(
    x=df_call_ls_an_bb.index,
    y=df_call_ls_an_bb["var_normalized"],
    mode='lines',
    name='LS Antithetic Price Variance'
))

fig.add_trace(go.Scatter(
    x=df_call_ls_cv_bb.index,
    y=df_call_ls_cv_bb["var_normalized"],
    mode='lines',
    name='LS Control Variate Price Variance'
))

fig.add_trace(go.Scatter(
    x=df_call_ls_an_cv_bb.index,
    y=df_call_ls_an_bb["var_normalized"],
    mode='lines',
    name='LS Antithetic Control Variate Price Variance'
))


# Laguerre
fig.add_trace(go.Scatter(
    x=df_call_ls_lbb.index,
    y=df_call_ls_lbb["var_normalized"],
    mode='lines',
    name='LS Laguerre Price Variance'
))

fig.add_trace(go.Scatter(
    x=df_call_ls_an_lbb.index,
    y=df_call_ls_an_lbb["var_normalized"],
    mode='lines',
    name='LS Laguerre Antithetic Price Variance'
))

fig.add_trace(go.Scatter(
    x=df_call_ls_cv_lbb.index,
    y=df_call_ls_cv_lbb["var_normalized"],
    mode='lines',
    name='LS Laguerre Control Variate Price Variance'
))

fig.add_trace(go.Scatter(
    x=df_call_ls_an_cv_lbb.index,
    y=df_call_ls_an_cv_lbb["var_normalized"],
    mode='lines',
    name='LS Laguerre Antithetic Control Variate Price Variance'
))

fig.update_layout(
    title="Variance Convergence by method of Longstaff Schwarz Algorithms",
    xaxis_title="Number of Simulations",
    yaxis_title="Average Variance",
    legend_title="Simulation methods"
)

fig.show()

## Quasi Longstaff Schwarz

In [27]:
fig = go.Figure()

# fig.add_trace(go.Scatter(
#     x=df_call_ls_bbq.index,
#     y=df_call_ls_bbq["mean"],
#     mode='lines',
#     name='Quasi LS Average Price'
# ))

# fig.add_trace(go.Scatter(
#     x=df_call_ls_an_bbq.index,
#     y=df_call_ls_an_bbq["mean"],
#     mode='lines',
#     name='Quasi LS Antithetic Average Price'
# ))

# fig.add_trace(go.Scatter(
#     x=df_call_ls_cv_bbq.index,
#     y=df_call_ls_cv_bbq["mean"],
#     mode='lines',
#     name='Quasi LS Control Variate Average Price'
# ))

# fig.add_trace(go.Scatter(
#     x=df_call_ls_an_cv_bbq.index,
#     y=df_call_ls_an_cv_bbq["mean"],
#     mode='lines',
#     name='Quasi LS Antithetic Control Variate Average Price'
# ))

#  # ------ Laguerre -----
# fig.add_trace(go.Scatter(
#     x=df_call_ls_lbbq.index,
#     y=df_call_ls_lbbq["mean"],
#     mode='lines',
#     name='Quasi LS Laguerre Average Price'
# ))

# fig.add_trace(go.Scatter(
#     x=df_call_ls_an_lbbq.index,
#     y=df_call_ls_an_lbbq["mean"],
#     mode='lines',
#     name='Quasi LS Laguerre Antithetic Average Price'
# ))

# fig.add_trace(go.Scatter(
#     x=df_call_ls_cv_lbbq.index,
#     y=df_call_ls_cv_lbbq["mean"],
#     mode='lines',
#     name='Quasi LS Laguerre Control Variate Average Price'
# ))

fig.add_trace(go.Scatter(
    x=df_call_ls_an_cv_lbbq.index,
    y=df_call_ls_an_cv_lbbq["mean"],
    mode='lines',
    name='Quasi LS Laguerre Antithetic Control Variate Average Price'
))


fig.update_layout(
    title="Price Convergence by method of Quasi Longstaff Schwarz Algorithms",
    xaxis_title="Number of Simulations",
    yaxis_title="Average Price",
    legend_title="Simulation methods"
)

fig.show()

In [28]:
fig = go.Figure()

fig.add_trace(go.Scatter(
    x=df_call_ls_bbq.index,
    y=df_call_ls_bbq["var_normalized"],
    mode='lines',
    name='Quasi LS Average Price'
))

fig.add_trace(go.Scatter(
    x=df_call_ls_an_bbq.index,
    y=df_call_ls_an_bbq["var_normalized"],
    mode='lines',
    name='Quasi LS Antithetic Price Variance'
))

fig.add_trace(go.Scatter(
    x=df_call_ls_cv_bbq.index,
    y=df_call_ls_cv_bbq["var_normalized"],
    mode='lines',
    name='Quasi LS Control Variate Price Variance'
))

fig.add_trace(go.Scatter(
    x=df_call_ls_an_cv_bbq.index,
    y=df_call_ls_an_cv_bbq["var_normalized"],
    mode='lines',
    name='Quasi LS Antithetic Control Variate Price Variance'
))

 # ------ Laguerre -----
fig.add_trace(go.Scatter(
    x=df_call_ls_lbbq.index,
    y=df_call_ls_lbbq["var_normalized"],
    mode='lines',
    name='Quasi LS Laguerre Price Variance'
))

fig.add_trace(go.Scatter(
    x=df_call_ls_an_lbbq.index,
    y=df_call_ls_an_lbbq["var_normalized"],
    mode='lines',
    name='Quasi LS Laguerre Antithetic Price Variance'
))

fig.add_trace(go.Scatter(
    x=df_call_ls_cv_lbbq.index,
    y=df_call_ls_cv_lbbq["var_normalized"],
    mode='lines',
    name='Quasi LS Laguerre Control Variate Price Variance'
))

fig.add_trace(go.Scatter(
    x=df_call_ls_an_cv_lbbq.index,
    y=df_call_ls_an_cv_lbbq["var_normalized"],
    mode='lines',
    name='Quasi LS Laguerre Antithetic Control Variate Price Variance'
))


fig.update_layout(
    title="Variance Convergence by method of Quasi Longstaff Schwarz Algorithms",
    xaxis_title="Number of Simulations",
    yaxis_title="Average Variance",
    legend_title="Simulation methods"
)

fig.show()

## Summary Statistics

Longstaff Schwarz for Mono European

In [41]:
dict = {
    "Standard LS" : df_call_ls,
    "Laguerre LS" : df_call_ls_l,
}
df_stats = summarize_results(dict, 750)
df_stats

                   Standard LS        Laguerre LS
mean                  6.743151           6.743151
var                   0.080594           0.080594
ci_interval  [6.5852 ; 6.9011]  [6.5852 ; 6.9011]

Longstaff Schwartz for Basket European

In [ ]:
dict = {
    "Standard LS" : df_call_ls_b,
    "Laguerre LS" : df_call_ls_lb,
}
df_stats = summarize_results(dict, 750)
df_stats

                    Standard LS         Laguerre LS
mean                  10.425609           10.466755
var                    0.389021            0.385886
ci_interval  [9.6631 ; 11.1881]  [9.7104 ; 11.2231]

In [45]:
# Laguerre
dict = {
    "LS" : df_call_ls_lb,
    "LS Antithetic" : df_call_ls_an_lb,
    "LS Control Variate" : df_call_ls_cv_lb,
    "LS Combined": df_call_ls_an_cv_lb
}
df_stats = summarize_results(dict, 750)
df_stats

,LS,LS Antithetic,LS Control Variate,LS Combined
mean,10.466755,10.776567,11.048152,11.194977
var,0.385886,0.339453,0.018378,0.033711
ci_interval,[9.7104 ; 11.2231],[10.1112 ; 11.4419],[11.0121 ; 11.0842],[11.1289 ; 11.2611]

Longstaff Schwarz for Basket Bermudan

In [46]:
dict = {
    "LS" : df_call_ls_bb,
    "LS Antithetic" : df_call_ls_an_bb,
    "LS Control Variate" : df_call_ls_cv_bb,
    "LS Combined": df_call_ls_an_cv_bb
}
df_stats = summarize_results(dict, 750)
df_stats

,LS,LS Antithetic,LS Control Variate,LS Combined
mean,10.425609,10.620707,14.863325,16.158456
var,0.389021,0.311309,0.10147,0.14373
ci_interval,[9.6631 ; 11.1881],[10.0105 ; 11.2309],[14.6644 ; 15.0622],[15.8767 ; 16.4402]

In [ ]:
# Laguerre
dict = {
    "Laguerre" : df_call_ls_lbb,
    "Laguerre Antithetic" : df_call_ls_an_lbb,
    "Laguerre Control Variate" : df_call_ls_cv_lbb,
    "Laguerre Combined": df_call_ls_an_cv_lbb
}
df_stats = summarize_results(dict, 750)
df_stats

,Laguerre,Laguerre Antithetic,Laguerre Control Variate,Laguerre Combined
mean,10.425609,10.830979,10.978966,11.194977
var,0.389021,0.368935,0.013921,0.033711
ci_interval,[9.6631 ; 11.1881],[10.1079 ; 11.5541],[10.9517 ; 11.0063],[11.1289 ; 11.2611]

Quasi Longstaff Schwarz for Basket Bermudan

In [50]:
dict = {
    "LS" : df_call_ls_bbq,
    "LS Antithetic" : df_call_ls_an_bbq,
    "LS Control Variate" : df_call_ls_cv_bbq,
    "LS Combined": df_call_ls_an_cv_bbq
}
df_stats = summarize_results(dict, 750)
df_stats

,LS,LS Antithetic,LS Control Variate,LS Combined
mean,2.215712,1.482943,14.905405,9.907924
var,0.004486,0.002829,0.108049,0.000803
ci_interval,[2.2069 ; 2.2245],[1.4774 ; 1.4885],[14.6936 ; 15.1172],[9.9064 ; 9.9095]

In [49]:
# Laguerre
dict = {
    "LS" : df_call_ls_lbbq,
    "LS Antithetic" : df_call_ls_an_lbbq,
    "LS Control Variate" : df_call_ls_cv_lbbq,
    "LS Combined": df_call_ls_an_cv_lbbq
}
df_stats = summarize_results(dict, 750)
df_stats

,LS,LS Antithetic,LS Control Variate,LS Combined
mean,0.822927,0.878111,10.949264,11.184128
var,0.001395,0.001548,0.014234,0.034233
ci_interval,[0.8202 ; 0.8257],[0.8751 ; 0.8811],[10.9214 ; 10.9772],[11.1170 ; 11.2512]